// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6yruBpS52eEZPiW4sp0XKvUPWEWI769E',
    appId: '1:721813050334:web:d5ab8e820cfce72776434f',
    messagingSenderId: '721813050334',
    projectId: 'todo-e9cf3',
    authDomain: 'todo-e9cf3.firebaseapp.com',
    storageBucket: 'todo-e9cf3.firebasestorage.app',
    measurementId: 'G-EZFEJR9HP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6j1rW_K2MV1Q2IXzffiqnP8bmmtVsnU4',
    appId: '1:721813050334:android:6b6c32548001123f76434f',
    messagingSenderId: '721813050334',
    projectId: 'todo-e9cf3',
    storageBucket: 'todo-e9cf3.firebasestorage.app',
  );
}
